[directory]
truncate_to_repo = false
truncation_symbol = "…/"
truncation_length = 9

[status]
disabled = false

[git_status]
disabled = true

[aws]
disabled = true

[env_var]
variable = "GOPATH"
style = "bold yellow"
format = "GOPATH=[$env_value]($style) "
